### PR TITLE
feat: enable fetching of secretsmanager-backed access key

### PR DESCRIPTION
**Pull request by francesco-racciatti**
# Description
This PR enables the fetching of SecretsManager-backed access keys.

The variable `access_key` can now handle secret references as described in [aws.doc.specifying-sensitive-data-secrets](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-secrets.html#secrets-application-retrieval), other than clear text keys.

Secret references have the following pattern:
```
arn:aws:secretsmanager:region:aws_account_id:secret:secret-name:json-key:version-stage:version-id
```
and contains two "pieces":
 - `arn:aws:secretsmanager:region:aws_account_id:secret:secret-name` which is the mandatory SecretARN;
 - `:json-key:version-stage:version-id` which is the optional part specifying the JSON Key, the version stage, and the version id of the secret.

Note that this PR:
 -  ensures backward compatibility (users can keep using clear text keys)
 -  marks `access_key` as sensitive to prevent secrets from being logged.

### Examples
For example, users can fetch the access key stored in the SecretsManager-backed secret `guess-my-secrets-QWerTY` as follows.

#### Referencing a plaintext secret
```shell
sysdig_orchestrator_agent.access_key = "arn:aws:secretsmanager:us-east-1:012345678987:secret:guess-my-secrets-QWerTY"
```
Since this references a plaintext secret, the optional part can be omitted.

#### Referencing a specific key
```shell
sysdig_orchestrator_agent.access_key = "arn:aws:secretsmanager:us-east-1:012345678987:secret:guess-my-secrets-QWerTY:MyJSONKey::"
```
Note that the trailing columns have to be defined even if we don’t want to fetch any particular label/version.

#### Referencing a specific key and version staging label
```shell
sysdig_orchestrator_agent.access_key = "arn:aws:secretsmanager:us-east-1:012345678987:secret:guess-my-secrets-QWerTY:MyJSONKey:AWSPREVIOUS:"
```

### CODE REVIEW

**Review by danhigham — APPROVED** [review]
This looks like the same commit from your other PR, but it still looks good.

**Review by danhigham — APPROVED** [review]
Tested this and it works just fine. Might be worth noting that the ARN for the secret looks slightly different to how you described in the PR, mine appears to be postfixed with 5 or 6 random characters, but it worked.

**Review by danhigham — APPROVED** [review]
Looks great!

**Comment by francesco-racciatti** [comment]
> This looks like the same commit from your other PR, but it still looks good 

That's because on the fork of mine this PR was based on the fmt branch, and not on the main branch.

**Comment by francesco-racciatti** [comment]
> Tested this and it works just fine. Might be worth noting that the ARN for the secret looks slightly different to how you described in the PR, mine appears to be postfixed with 5 or 6 random characters, but it worked 

AWS appends 6 random chars to to the custom secret name. The secretARN contains such random chars.

Note that this PR relies on secret references (made on top of secretsARNs)

**Comment by francesco-racciatti** [comment]
cc @sysdiglabs/team-tools-agent

**Review by aroberts87 — APPROVED** [review]
I'm not well versed in secretsmanager, but this all looks reasonable. 🙂

**Pull request merged**
